package-lock.json
package.json

Update builder dependency to 0.0.2

[INTERNAL] Update @ui5/builder dependency

---

README.md
bin/ui5.js
package-lock.json
package.json

Asynchronously checks for newer ui5-cli releases and notifies user on
next run. Also see: https://github.com/yeoman/update-notifier#how

[FEATURE] Add update notifier

---

README.md
package.json

To allow usage of fs.copyFile() API

[INTERNAL] Update min Node.js version to >=8.5

---

.chglog/config.yml
.chglog/release-config.yml

Scope may contain special characters

[INTERNAL] CHANGELOG: Fix scope detection in commit messages

---

README.md

[INTERNAL] README: Add general information links

---

README.md
lib/cli/commands/versions.js
package-lock.json

show versions of all UI5 tooling packages.
Fixes: #64

[FEATURE] Versions command

---

README.md
lib/cli/commands/serve.js
lib/cli/commands/versions.js

[INTERNAL] UA Review README.md

---

lib/cli/commands/build.js
lib/cli/commands/serve.js
lib/cli/commands/tree.js
test/lib/cli/commands/serve.js

Relevant API change: https://github.com/SAP/ui5-project/pull/96

[INTERNAL] Adapt UI5 normalizer calls to API change

---

npm-shrinkwrap.json

Mainly to resolve npm "extraneous dependency dir-glob" errors when
executing npm ls

[INTERNAL] npm: Update transitive dependencies

---

package.json

Include npm-shrinkwrap.json in the package published to the npm
registry.
Related to https://github.com/SAP/ui5-cli/pull/130 and https://github.com/SAP/ui5-cli/issues/128

[FEATURE] Publish npm-shrinkwrap.json

---

README.md
lib/cli/commands/build.js
test/lib/cli/commands/build.js

Depends on https://github.com/SAP/ui5-builder/pull/42

[INTERNAL] Build: Add 'jsdoc' command

---

README.md
lib/cli/commands/serve.js
test/lib/cli/commands/serve.js

[FEATURE] Add 'sap-csp-policies' option to 'serve' command.

---

.editorconfig

Fix definition for yml in .editorconfig.

[INTERNAL] .editorconfig fix

---

bin/ui5.js
lib/cli/middlewares/logger.js
lib/cli/version.js
test/lib/cli/middlewares/logger.js

[FEATURE] Log CLI version when using --verbose option

---

lib/cli/commands/remove.js
lib/framework/remove.js
lib/framework/updateYaml.js
test/lib/cli/commands/remove.js
test/lib/framework/remove.js
test/lib/framework/updateYaml.js

Followup of #315.
Add ui5 remove command which removes libraries from
the framework libraries section in the ui5.yaml.

[FEATURE] Add "ui5 remove" command

---

bin/ui5.js
test/lib/cli/commands/base.js

Fixes: https://github.com/SAP/ui5-cli/issues/323

[FIX] Allow use of `--no-update-notifier` flag

---

.chglog/consolidate-changelogs.js

Fix regex to correctly match empty changelogs.

[INTERNAL] Consolidated changelog: Correctly match empty changelogs

---

lib/framework/updateYaml.js
test/lib/framework/updateYaml.js

Fixes: https://github.com/SAP/ui5-tooling/issues/474

[FIX] ui5 use: Corrupt UI5 configuration

---

lib/init/init.js
test/lib/init/init.js

[INTERNAL] init: Use specVersion 2.5

---

lib/init/init.js
test/lib/init/init.js

[INTERNAL] init: Use specVersion 2.6

---

lib/cli/commands/build.js
test/lib/cli/commands/build.js

Enables build of CSS variables via experimental CLI flag.
BLI: CPOUI5FOUNDATION-346

[FEATURE] Add build flag "--experimental-css-variables" to enable UI5 builds with CSS Variables

---

.eslintrc.js
bin/ui5.js
lib/cli/update-notifier.js
npm-shrinkwrap.json
package.json

Upgrades transitive dependency "got" to resolve CVE-2022-33987.

[FIX] Upgrade update-notifier to solve security vulnerabilities

---

bin/ui5.js
test/bin/ui5.js
test/lib/cli/commands/base.js

Regression caused by https://github.com/SAP/ui5-cli/pull/533
Fixes: https://github.com/SAP/ui5-tooling/issues/663

[FIX] SyntaxError: Unexpected token '.' in Node.js v12

---

npm-shrinkwrap.json
package.json

Increase package.json version to beta

[INTERNAL] package.json: Change pre-release from 'alpha' to 'beta'

---

lib/framework/add.js
lib/framework/remove.js
lib/framework/use.js
lib/framework/utils.js
test/lib/framework/add.js
test/lib/framework/remove.js
test/lib/framework/use.js
test/lib/framework/utils.js

See https://github.com/SAP/ui5-project/pull/431

[INTERNAL] Adapt to new Specification#getSpecVersion implementation

---

lib/cli/commands/build.js
test/lib/cli/commands/build.js

See https://github.com/SAP/ui5-project/pull/524

[INTERNAL] build: Rename 'complexDependencyIncludes' param

---

lib/cli/commands/tree.js
test/lib/cli/commands/tree.js

See https://github.com/SAP/ui5-project/pull/527

[INTERNAL] Adapt to new ProjectGraph API

---

lib/cli/base.js
lib/cli/middlewares/logger.js
lib/framework/remove.js
lib/framework/updateYaml.js
npm-shrinkwrap.json
package.json
test/lib/cli/base.js
test/lib/cli/middlewares/logger.js

See https://github.com/SAP/ui5-logger/pull/371

[INTERNAL] Align with @ui5/logger changes to named exports

---

lib/cli/commands/tree.js
lib/framework/add.js
lib/framework/updateYaml.js
lib/framework/use.js
test/lib/cli/commands/tree.js
test/lib/framework/add.js
test/lib/framework/remove.js
test/lib/framework/updateYaml.js
test/lib/framework/use.js

API got renamed in https://github.com/SAP/ui5-project/pull/557

[INTERNAL] Use Specification#getRootPath

---

lib/cli/commands/serve.js

See: https://github.com/SAP/ui5-server/pull/580

[INTERNAL] CSP: Update description of sap-csp-policies parameter

---

lib/cli/commands/config.js

They were missing the 'config' command

[INTERNAL] config: Fix command examples

---

azure-pipelines.yml
lib/cli/commands/build.js
lib/cli/commands/serve.js
lib/cli/commands/tree.js
lib/cli/commands/use.js

Updates according to new features via https://github.com/SAP/ui5-project/pull/649
JIRA: CPOUI5FOUNDATION-722

[FIX] Update help description for "use" and "--framework-version"

---

lib/init/init.js
test/lib/init/init.js

Initialize ui5.yaml with the latest specVersion = 3.2

[INTERNAL] Init ui5.yaml with specVersion: 3.2

---

.chglog/release-config.yml
jsdoc.json
lib/init/init.js
package.json
test/lib/init/init.js

[INTERNAL] Setup main branch for UI5 Tooling V4

---

npm-shrinkwrap.json
package.json

[INTERNAL] package.json: set version to 4.0.0-alpha

---

lib/init/init.js
test/lib/init/init.js

[INTERNAL] Init ui5.yaml with specVersion: 4.0

---

.chglog/CHANGELOG.tpl.md
CHANGELOG.md

[INTERNAL] .chglog/CHANGELOG.tpl.md: Add missing v3 releases

---

.licensee.json

Follow-up of https://github.com/SAP/ui5-cli/pull/730

[INTERNAL] licensee: Remove exceptions

---

lib/cli/commands/build.js

Fixes https://github.com/SAP/ui5-tooling/issues/1077

[INTERNAL] Fix layout in UI5 CLI Reference
