SAP/ui5-cli

- README.md
- bin/ui5.js
- package-lock.json
- package.json
- test/lib/cli/commands/base.js
When running the global "ui5" command while a local @ui5/cli version is
installed for the current project, the local one should be preferred.
Fixes: #58
> [FEATURE] Prefer local over global CLI version

- .eslintrc.js
- index.js
- jsdoc.json
- lib/cli/middlewares/base.js
- lib/cli/middlewares/logger.js
- lib/init/init.js
- package-lock.json
- package.json
Also:
- prevent use of unkown tags
- add some docdash specific page options
> [INTERNAL] JSDoc: Make API private by default

- npm-shrinkwrap.json
- package.json
Required for `ui5 versions` command. This should also help ensuring
correct dependency updates when releasing UI5 Tooling modules.
> [DEPENDENCY] Add direct dependency to @ui5/fs

- README.md
- lib/cli/commands/base.js
- lib/cli/commands/build.js
- lib/cli/commands/tree.js
- npm-shrinkwrap.json
- test/lib/cli/commands/tree.js
Internally, dependency trees are always deduped. However, for debugging
dependency related issues in a project, it might be helpfull to still
see "deduped" nodes (currently the default).
Setting the "--dedupe" flag will remove deduped nodes from the tree
output.
- Also added "--log-level" alias to "--loglevel"
- Also cleaned up some defaults and documentation
> [FEATURE] ui5 tree: Add dedupe option

- npm-shrinkwrap.json
- package.json
- test/lib/cli/commands/base.js
- test/lib/cli/commands/build.js
- test/lib/cli/commands/init.js
- test/lib/cli/commands/serve.js
- test/lib/cli/commands/tree.js
- test/lib/cli/commands/versions.js
- test/lib/cli/middlewares/base.js
- test/lib/cli/middlewares/logger.js
- test/lib/init/init.js
- test/lib/utils/fsHelper.js
Relevant changelogs:
https://github.com/avajs/ava/releases/tag/v1.0.1
https://github.com/avajs/ava/releases/tag/v2.0.0
Relevant changes:
- AVA now requires at least Node.js 8.9.4. We require only 8.5.
However, since this is a devDependency I guess we can live with that.
- t.throws() does not accept promises anymore. Use t.throwsAsync()
- Test titles now must be unique
> [INTERNAL] Bump ava to 2.0.0

- lib/cli/commands/serve.js
- test/lib/cli/commands/serve.js
The default certificate key/cert paths were using the $HOME variable
which was not replaced with the actual homedir of the user.
This caused creating a "$HOME" folder within the project which was not
intended.
Furthermore this can be dangerous in case someone wants to remove that
folder with `rm -rf`, as this might cause the homedir to be removed in
case no single quotes are used.
> [FIX] serve: Create SSL certificate in user homedir

- lib/cli/commands/build.js
- test/lib/cli/commands/build.js
This exposes the UI5 Builders cleanDest parameter that was added
with https://github.com/SAP/ui5-builder/pull/306.
Usage: `ui5 build --clean-dest`
Description: If present, clean the destination directory before building
Default: `false`
> [FEATURE] ui5 build: Add --clean-dest option

- lib/cli/commands/serve.js
- test/lib/cli/commands/serve.js
A project configuration can now define a default port for each HTTP and
HTTPS server.
**ui5.yaml example:**
```yaml
server:
settings:
httpPort: 1337
httpsPort: 1443
```
> [FEATURE] Add server settings

- npm-shrinkwrap.json
- package.json
This reverts commit 5a8f46e04a7506f6dd97fa35fb0fe7a0dd34ecac (https://github.com/SAP/ui5-cli/pull/238).
Breaking change "do not allow additional positionals in strict mode"
affects "ui5 serve"
Before:
"ui5 serve foo" => Starts server
After 5a8f46e:
"ui5 serve foo" => Displays help followed by "Unknown argument: foo"
> [INTERNAL] Revert "Bump yargs from 13.3.0 to 14.0.0"

- lib/cli/commands/build.js
- lib/cli/commands/serve.js
- lib/cli/commands/tree.js
- test/lib/cli/commands/build.js
- test/lib/cli/commands/serve.js
- test/lib/cli/commands/tree.js
Depends on https://github.com/SAP/ui5-project/pull/265
> [FEATURE] Add --framework-version option

- lib/framework/updateYaml.js
- test/lib/framework/updateYaml.js
In some cases the use/add command has failed to update the ui5.yaml
file, e.g. when some configuration is after the "framework" section.
> [FIX] ui5 use/add: Fix updating ui5.yaml file

- lib/cli/commands/use.js
- test/lib/cli/commands/use.js
Validation of the version is now only done within ui5-project
> [FIX] ui5 use: Allow using versions according to Semantic Versioning

- lib/cli/commands/serve.js
- test/lib/cli/commands/serve.js
Add option to use csp-report-path to create csp reports for server.
See: SAP/ui5-server/pull/323
Sample call
```bash
ui5 serve --serve-csp-reports
```
> [FEATURE] ui5 serve: Add serve-csp-reports option

- azure-pipelines.yml
- npm-shrinkwrap.json
- package.json
Due to a bug in npm, acorn-jsx can't find the correct version of acorn.
Downgrading to ava@3.11 solves the issue as only one acorn version (v7) is present.
Also adding an 'npm ls' check to detect such issues before they get merged into master.
> [INTERNAL] Fix missing peerDependency to acorn / Add CI check

- .chglog/consolidate-changelogs.js
To make it clear that the sub-changelog belongs to a certain module.
> [INTERNAL] Consolidated changelog: Update formatting

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/config.yml
- README.md
- lib/cli/commands/base.js
- test/lib/cli/commands/base.js
Related to https://github.com/SAP/ui5-tooling/pull/273 and https://github.com/SAP/ui5-cli/issues/392
> [INTERNAL] Error handling: Recommend ui5-tooling repository for creating issue

- lib/cli/commands/serve.js
Since the use of the --accept-remote-connections parameter might
indicate the intent to use the server in a productive environment, we
warn users not to do that.
And even in development environments, exposing the server to the network
might be a security risk for the system. Therefore we also warn on some
of those aspects.
Resolves: https://github.com/SAP/ui5-tooling/issues/326
> [INTERNAL] ui5 serve: Log warning when accepting remote connections

- lib/cli/commands/use.js
- test/lib/cli/commands/use.js
Fixes: https://github.com/SAP/ui5-tooling/issues/496
> [FIX] `ui5 use <framework>` should default to `latest`

- lib/cli/commands/build.js
Also mention that self-contained should be used in conjunction with --all
in order to ensure that files which can't be bundled are also part of the
build result.
> [INTERNAL] Docs: Add "ui5 build self-contained" example

- test/lib/cli/commands/base.js
It seems that with node v16.10.0 the error message for accessing a
property of null changed from
`Cannot read property 'foo' of null`
to
`Cannot read properties of null (reading 'foo')`
Adapted the test to throw our own exception with a stable error message.
Our master CI is currently failing because of this
> [INTERNAL] base: Fix test relying on Node TypeError message

- bin/ui5.js
- test/bin/ui5.js
Support to use the UI5 Tooling with a Node.js pre-release
version. In case of using a pre-release version a warning
will be reported that for productive use only stable versions
should be used.
Fixes: https://github.com/SAP/ui5-tooling/issues/550
> [FIX] Allow Node.js pre-release versions

- .chglog/consolidate-changelogs.js
- package.json
The CLI needs the changelog files of all modules to create a
consolidated changelog.
Since npm v7 the CHANGELOG file is not always published anymore.
See: https://github.com/npm/npm-packlist/pull/61
> [INTERNAL] npm release: Add missing CHANGELOG file

- .eslintrc.js
- npm-shrinkwrap.json
- package.json
- test/bin/ui5.js
- test/lib/cli/commands/base.js
- test/lib/cli/commands/versions.js
- test/lib/cli/middlewares/base.js
- test/lib/framework/add.js
- test/lib/framework/updateYaml.js
- test/lib/framework/use.js
Introducing [eslint-plugin-ava](https://github.com/avajs/eslint-plugin-ava/) to avoid common pitfalls when writing powerful ava tests.
- Add plugin to eslint config and package.json
- Restructure current code base to latest recommendations
> [INTERNAL] use eslint-plugin-ava and cleanup test-suite

- .chglog/consolidate-changelogs.js
This file was not converted to ESM and with that for release `3.0.0-alpha.15` no changelog was generated.
> [INTERNAL] Transform 'consilidate-changelogs.js' to native ESM

- lib/cli/cli.js
- test/bin/ui5.js
- test/lib/cli/cli.js
This is done to improve performance by reducing the overhead of loading
the dependency in cases where it is not needed.
Based on changes for v2 via https://github.com/SAP/ui5-cli/pull/533
> [INTERNAL] Only import update-notifier when it's not disabled

- .chglog/consolidate-changelogs.js
If a dependencies changelog is empty, we still need to add a newline
after the bullet point for the dependency version bump.
> [INTERNAL] consolidate-changelogs.js: Fix missing newline

- lib/cli/commands/build.js
Function is deprecated as per https://github.com/SAP/ui5-logger/pull/353
> [INTERNAL] Remove call to @ui5/logger#setShowProgress

- lib/framework/updateYaml.js
- test/lib/framework/updateYaml.js
See added comment for details. This seems to be an overlooked behavior
of data-with-position. It can also be observed in the respective tests:
The 'str' array ends in line 11, column 3:
https://github.com/gicentre/litvis/blob/855268e33ef40be1b03062eacefad79fadbf6b4e/packages/data-with-position/src/__fixtures__/fromYaml/basic.config.ts#L73
Which is actually the beginning of the next node:
https://github.com/gicentre/litvis/blob/855268e33ef40be1b03062eacefad79fadbf6b4e/packages/data-with-position/src/__fixtures__/fromYaml/basic.yaml#L11
> [FIX] updateYaml: Array update preserves indentation of following node

- lib/cli/base.js
- lib/cli/commands/build.js
- lib/cli/commands/serve.js
- lib/cli/commands/tree.js
- test/lib/cli/commands/build.js
- test/lib/cli/commands/serve.js
- test/lib/cli/commands/tree.js
Depends on https://github.com/SAP/ui5-project/pull/494
> [INTERNAL] Add workspace arguments

- lib/cli/base.js
- test/lib/cli/base.js
Otherwise terminal settings are not restored (e.g. cursor disappears).
Depends on https://github.com/SAP/ui5-logger/pull/375
> [INTERNAL] base: Stop ConsoleWriter on exceptions

- lib/framework/add.js
- lib/framework/use.js
- lib/framework/utils.js
- test/lib/framework/add.js
- test/lib/framework/use.js
- test/lib/framework/utils.js
Enables commands like `ui5 use 1.114.0-SNAPSHOT`, `ui5 use 1.112-SNAPSHOT` (resolving to the latest patch) and `ui5 use latest-snapshot`
Depends on https://github.com/SAP/ui5-project/pull/570
> [INTERNAL] add/use: Integrate Sapui5MavenSnapshotResolver

- lib/cli/commands/build.js
Only can find the command `--include-dependencies` in this line and in the documentation.  
Should it be `--include-all-dependencies` ?
+ Especially the [How to Contribute](https://github.com/SAP/ui5-tooling/blob/main/CONTRIBUTING.md#how-to-contribute) section
> [INTERNAL] use correct option to show in docs

- lib/cli/base.js
- lib/cli/commands/build.js
- lib/cli/commands/serve.js
- lib/cli/commands/tree.js
- test/lib/cli/commands/build.js
- test/lib/cli/commands/serve.js
- test/lib/cli/commands/tree.js
Expose cache-mode API parameter via CLI. See also:
https://github.com/SAP/ui5-project/pull/607
> [FEATURE] SNAPSHOT Consumption: Add cache-mode parameter

- lib/cli/base.js
- lib/cli/commands/build.js
- lib/cli/commands/serve.js
- lib/cli/commands/tree.js
As per feedback provided in
https://github.com/SAP/ui5-tooling/issues/841#issuecomment-1613164131,
explain that the provided dependency names must match the ui5.yaml names
and not the npm module names.
> [INTERNAL] build: Add details to include-dependency options

- test/lib/cli/commands/config.js
Extending Configuration.js in [ui5-project](https://github.com/SAP/ui5-project) with more options, breaks some tests as the `toJson()` method now returns more properties.
That's why we need to be more precise when comparing values, but not the whole object.
> [INTERNAL] Make config tests more robust

- lib/cli/commands/config.js
- test/lib/cli/commands/config.js
Options are now properly read from the @ui5/project Configuration class
in order to be decoupled from future changes.
Some code could be removed as the checks are done via yargs.
See: https://github.com/SAP/ui5-project/pull/642
JIRA: CPOUI5FOUNDATION-716
> [FIX] ui5 config: Allow usage of all Configuration options

- lib/cli/commands/init.js
- test/fixtures/init/application/ui5.yaml
- test/lib/cli/commands/init.js
Use `"` instead of `'` when writing yaml files.
Team decided to use double quotes.
> [FIX] ui5.yaml: Use double quotes for string values

- lib/init/init.js
- test/lib/init/init.js
Fixes: https://github.com/SAP/ui5-tooling/issues/306
> [FIX] ui5 init: Improve error message

- npm-shrinkwrap.json
- package.json
- test/bin/ui5.js
Fixes: https://github.com/SAP/ui5-tooling/issues/891
Node's module loading has changed since 20.6.xx. As `esmock` is unable to properly mock dynamic imports within CommonJS modules, we need to use another alternative for this test. `testdouble` seems to work pretty well for that case, but for NodeJS versions below 20.6.xx it needs a `--loader` flag and we already use that for `esmock`.
The solution would be to use the old mocking for older NodeJs versions and `testdouble` for the ones after 20.6.xx (no flag required here): https://github.com/testdouble/testdouble.js/blob/main/docs/7-replacing-dependencies.md#how-module-replacement-works-for-es-modules-using-import
> [INTERNAL] New dynamic import mock for NodeJS >= 20.6.xx

- lib/cli/commands/build.js
- test/lib/cli/base.js
- test/lib/cli/commands/build.js
New CLI `build` option `--output-style`. Whether to omit the /resources/\<namespace\> directory structure in the build output.
Resolves https://github.com/SAP/ui5-tooling/issues/507
Depends on: https://github.com/SAP/ui5-project/pull/624
> [FEATURE] Add option to redefine output directory structure

- .licensee.json
- npm-shrinkwrap.json
- package.json
Only allow dependencies with licenses listed as Gold, Silver or Bronze at https://blueoakcouncil.org/list
Generally those should not cause us any trouble. Restricting this further to specific licenses currently in use by our dependencies might cause unnecessary maintenance efforts in the future due to the great variety of licenses being used.
Exceptions added for [`callsite`](https://www.npmjs.com/package/callsite) (uses MIT) and [`yesno`](https://www.npmjs.com/package/yesno) (uses BSD).
> [INTERNAL] package.json: Add license check for dependencies

- .chglog/consolidate-changelogs.js
- .github/workflows/github-ci.yml
- azure-pipelines.yml
- lib/cli/commands/versions.js
- npm-shrinkwrap.json
- package.json
- test/lib/cli/base.js
- test/lib/cli/commands/config.js
- test/lib/cli/middlewares/logger.js
- test/lib/package-exports.js
BREAKING CHANGE:
Support for older Node.js and npm releases has been dropped.
Only Node.js 20.11.x and >=21.2.0 as well as npm v10 or higher are supported.
JIRA: CPOUI5FOUNDATION-800
> [BREAKING] Require Node.js 20.11.x/>=21.2.0 and npm >=10 

- lib/framework/utils.js
- test/lib/framework/utils.js
BREAKING CHANGE:
`@ui5/project`'s Installers' and Resolvers' argument `ui5HomeDir` is now renamed to `ui5DataDir`
JIRA: CPOUI5FOUNDATION-802
Relates to: https://github.com/SAP/ui5-tooling/issues/701
Depends on: https://github.com/SAP/ui5-project/pull/707
> [BREAKING] Rename ui5HomeDir to ui5DataDir in APIs

- npm-shrinkwrap.json
- package.json
There is no actual need to increase the minimum npm version. Lockfile v3 is already supported
> [INTERNAL] package.json: Allow npm >= v8

- .licensee.json
All three packages are licensed under the MIT license, but the package.json file is missing the license field.
PRs to add the license field have already been opened for all three packages.
> [INTERNAL] licensee: Add exception for new deps

- npm-shrinkwrap.json
- package.json
This came via the in-range update of the `update-notifier` package from v7.1.0 to v7.2.0.
Root cause: https://github.com/sindresorhus/cli-boxes/issues/11
> [FIX] Node.js ExperimentalWarning shown on console

- npm-shrinkwrap.json
- package.json
Follow-up of https://github.com/SAP/ui5-cli/pull/731
The problematic dependency is not used anymore by the "boxen" package.
> [INTERNAL] Switch back to latest version of update-notifier

- lib/cli/base.js
The CLI now also prints the stack trace of the error cause of
unexpected errors or when verbose logging is enabled.
This improves error analysis in case an error is caught and re-thrown
as "cause" of a new error, e.g. during minification.
> [FIX] Print error cause stack trace

- lib/cli/commands/versions.js
- test/lib/cli/commands/versions.js
If verbose logging is enabled, also show the local  path of each
UI5 Tooling module. This can be helpful to debug dev environment issues.
> [INTERNAL] versions: Include package location in verbose mode
